import type { Metadata } from 'next';
import { Noto_Sans_Display } from 'next/font/google';
import './globals.css';
import dynamic from 'next/dynamic';
import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from 'sonner';

const noto = Noto_Sans_Display({ subsets: ['latin'] });

// ⬇️ Carga ClerkProvider solo en el cliente
const ClientClerkProvider = dynamic(
	() => import('@clerk/nextjs').then((mod) => mod.ClerkProvider),
	{ ssr: false },
);

export const metadata: Metadata = {
	title: 'RDN Rivera',
	description: 'Generated by Alberto Castillo',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={noto.className}>
					<ThemeProvider
						attribute="class"
						enableSystem
						disableTransitionOnChange
					>
						<Toaster />
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
